/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_maluta_libusbproject_NativeLib */

#ifndef _Included_io_github_maluta_libusbproject_NativeLib
#define _Included_io_github_maluta_libusbproject_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_maluta_libusbproject_NativeLib
 * Method:    listDevices
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_maluta_libusbproject_NativeLib_listDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
